SELECT
 OWNER
,OBJECT_TYPE
,OBJECT_NAME
,MESSAGE
FROM (
SELECT
 OWNER
,OBJECT_TYPE
,OBJECT_NAME
,'Exists in KFPRD but not in KFIMP' Message
FROM DBA_OBJECTS@uazkfprd
MINUS
SELECT
 OWNER
,OBJECT_TYPE
,OBJECT_NAME
,'Exists in KFPRD but not in KFIMP'
FROM DBA_OBJECTS
UNION
SELECT
 OWNER
,OBJECT_TYPE
,OBJECT_NAME
,'Exists in KFIMP but not in KFPRD'
FROM DBA_OBJECTS
MINUS
SELECT
 OWNER
,OBJECT_TYPE
,OBJECT_NAME
,'Exists in KFIMP but not in KFPRD'
FROM DBA_OBJECTS@uazkfprd)
WHERE
    OWNER = 'KULOWNER'
AND SUBSTR(OBJECT_NAME,1,5) NOT IN ('RUPD$','MLOG$')
AND OBJECT_TYPE <> 'MATERIALIZED VIEW'
AND OBJECT_NAME NOT LIKE 'SYS%'
AND OBJECT_NAME NOT LIKE 'I_SNAP$%'
ORDER BY 1,2,3 
