SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T;
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-JAN-16' and '01-JAN-17';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-JAN-16' and '05-JAN-17';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-DEC-16' and '31-DEC-17';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-NOV-16' and '01-NOV-17';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-OCT-16' and '01-OCT-17';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-JAN-15' and '01-JAN-16';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-JAN-14' and '01-JAN-15';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-JAN-13' and '01-JAN-14';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-JAN-12' and '01-JAN-13';
SELECT SUM(ACCT_NET_AMT) FROM TAX_PAYMENT_T where DISB_DT between '01-JAN-11' and '01-JAN-12';

