set colsep ','     
set pagesize 0   
set trimspool on 
set headsep off     

SELECT CURRENT_TIMESTAMP FROM DUAL;


spool ./data/FP_PRCRMNT_CARD_TRN_T_3.csv

select SUM(DOC_TOTAL_AMT),
SUM(RN_ORIG_CRNCY_AMT),
SUM(RN_STLMNT_AMT),
SUM(RN_SALES_TAX_AMT),
SUM(DOC_CARD_CYCLE_AMT_LMT),
SUM(AX_AMT),
SUM(ISCOUNT_AMT),
SUM(REIGHT_AMT),
SUM(UTY_AMT),
SUM(SER_AMT),
SUM(UEL_SALE_AMT),
SUM(UEL_DISCOUNT_AMT),
SUM(AX_AMT_1),
SUM(AX_AMT_2),
SUM(OTAL_AMT),
SUM(RE_PAID_AMT),
SUM(DJUSTMENT_AMT),
SUM(DJUST_AMT),
SUM(OTAL_TAX_AMT)
from kulowner.FP_PRCRMNT_CARD_TRN_T;

spool off

spool ./data/FP_PRCRMNT_CARD_TRN_T_7.csv

select SUM(DOC_TOTAL_AMT),
SUM(RN_ORIG_CRNCY_AMT),
SUM(RN_STLMNT_AMT),
SUM(RN_SALES_TAX_AMT),
SUM(DOC_CARD_CYCLE_AMT_LMT),
SUM(AX_AMT),
SUM(ISCOUNT_AMT),
SUM(REIGHT_AMT),
SUM(UTY_AMT),
SUM(SER_AMT),
SUM(UEL_SALE_AMT),
SUM(UEL_DISCOUNT_AMT),
SUM(AX_AMT_1),
SUM(AX_AMT_2),
SUM(OTAL_AMT),
SUM(RE_PAID_AMT),
SUM(DJUSTMENT_AMT),
SUM(DJUST_AMT),
SUM(OTAL_TAX_AMT)
from kulowner.FP_PRCRMNT_CARD_TRN_MT@DBLINK;

spool off