set colsep ','     
set pagesize 0   
set trimspool on 
set headsep off     
set numwidth 20

SELECT CURRENT_TIMESTAMP FROM DUAL;

spool ./data/FP_PRCRMNT_CARD_TRN_T_3.csv

select
SUM(FDOC_TOTAL_AMT),
SUM(TRN_ORIG_CRNCY_AMT),
SUM(TRN_STLMNT_AMT),
SUM(TRN_SALES_TAX_AMT),
SUM(TAX_AMT),
SUM(DISCOUNT_AMT),
SUM(FREIGHT_AMT),
SUM(DUTY_AMT),
SUM(USER_AMT),
SUM(FUEL_SALE_AMT),
SUM(FUEL_DISCOUNT_AMT),
SUM(TAX_AMT_1),
SUM(TAX_AMT_2),
SUM(TOTAL_AMT),
SUM(PRE_PAID_AMT),
SUM(ADJUSTMENT_AMT),
SUM(ADJUST_AMT),
SUM(TOTAL_TAX_AMT)
from FP_PRCRMNT_CARD_TRN_T;


spool off

spool ./data/FP_PRCRMNT_CARD_TRN_T_7.csv

select
SUM(FDOC_TOTAL_AMT),
SUM(TRN_ORIG_CRNCY_AMT),
SUM(TRN_STLMNT_AMT),
SUM(TRN_SALES_TAX_AMT),
SUM(TAX_AMT),
SUM(DISCOUNT_AMT),
SUM(FREIGHT_AMT),
SUM(DUTY_AMT),
SUM(USER_AMT),
SUM(FUEL_SALE_AMT),
SUM(FUEL_DISCOUNT_AMT),
SUM(TAX_AMT_1),
SUM(TAX_AMT_2),
SUM(TOTAL_AMT),
SUM(PRE_PAID_AMT),
SUM(ADJUSTMENT_AMT),
SUM(ADJUST_AMT),
SUM(TOTAL_TAX_AMT)
from kulowner.FP_PRCRMNT_CARD_TRN_MT@DBLINK;

spool off