--Indicates the AP_CRDT_MEMO_ACCT_CHG_T table has no schema changes.
SELECT * FROM (
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='AP_CRDT_MEMO_ACCT_CHG_T'
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='AP_CRDT_MEMO_ACCT_CHG_T'
    )
    UNION
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='AP_CRDT_MEMO_ACCT_CHG_T' 
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='AP_CRDT_MEMO_ACCT_CHG_T'
    )
) ORDER BY TABLE_NAME, COLUMN_NAME;

--Shows each table individually for verification.
SELECT TABLE_NAME AS "KFS3 TABLE_NAME"        ,COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS          WHERE TABLE_NAME='AP_CRDT_MEMO_ACCT_CHG_T';
SELECT TABLE_NAME AS "Financials 7 TABLE_NAME",COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS@KFS7GOLD WHERE TABLE_NAME='AP_CRDT_MEMO_ACCT_CHG_T';

--Table Data Comparison Example. No Rows differ.
SELECT * FROM AP_CRDT_MEMO_ACCT_CHG_T
MINUS
SELECT * FROM AP_CRDT_MEMO_ACCT_CHG_T@KFS7GOLD;


--Indicates the CM_AST_TRNFR_DOC_T table has a column with only a data length change.
SELECT * FROM (
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='CM_AST_TRNFR_DOC_T'
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='CM_AST_TRNFR_DOC_T'
    )
    UNION
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='CM_AST_TRNFR_DOC_T' 
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='CM_AST_TRNFR_DOC_T'
    )
) ORDER BY TABLE_NAME, COLUMN_NAME;

--Shows each table individually for verification.
SELECT TABLE_NAME AS "KFS3 TABLE_NAME"        ,COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS          WHERE TABLE_NAME = 'CM_AST_TRNFR_DOC_T' ORDER BY COLUMN_NAME;
SELECT TABLE_NAME AS "Financials 7 TABLE_NAME",COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS@KFS7GOLD WHERE TABLE_NAME = 'CM_AST_TRNFR_DOC_T' ORDER BY COLUMN_NAME;

--Because only column data lengths were changed, * can be used.
--Table Data Comparison Example. No Rows differ.
SELECT * FROM CM_AST_TRNFR_DOC_T
MINUS
SELECT * FROM CM_AST_TRNFR_DOC_T@KFS7GOLD;



--Indicates the CG_AWD_PRJDR_T table has a column with a data type change.
SELECT * FROM (
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='CG_AWD_PRJDR_T'
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='CG_AWD_PRJDR_T'
    )
    UNION
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='CG_AWD_PRJDR_T' 
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='CG_AWD_PRJDR_T'
    )
) ORDER BY TABLE_NAME, COLUMN_NAME;

--Shows each table individually for verification.
SELECT TABLE_NAME AS "KFS3 TABLE_NAME"        ,COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS          WHERE TABLE_NAME = 'CG_AWD_PRJDR_T' ORDER BY COLUMN_NAME;
SELECT TABLE_NAME AS "Financials 7 TABLE_NAME",COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS@KFS7GOLD WHERE TABLE_NAME = 'CG_AWD_PRJDR_T' ORDER BY COLUMN_NAME;

--Because there are data type differences, only the columns that match data types can be compared. Columns with differing data types can be compared if there is a conversion method available.
--Table Data Comparison Example.
SELECT CGAWD_PRJDRPRJ_TTL, CGAWD_PRMPRJDR_IND, CGPRPSL_NBR, OBJ_ID, PERSON_UNVL_ID, ROW_ACTV_IND, VER_NBR 
    FROM CG_AWD_PRJDR_T
MINUS
SELECT CGAWD_PRJDRPRJ_TTL, CGAWD_PRMPRJDR_IND, TO_NUMBER(CGPRPSL_NBR), OBJ_ID, PERSON_UNVL_ID, ROW_ACTV_IND, VER_NBR 
    FROM CG_AWD_PRJDR_T@KFS7GOLD;



--Indicates the AP_AUTO_APRV_EXCL_T table has column differences.
SELECT * FROM (
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='AP_AUTO_APRV_EXCL_T'
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='AP_AUTO_APRV_EXCL_T'
    )
    UNION
    (
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS@KFS7GOLD 
            WHERE TABLE_NAME='AP_AUTO_APRV_EXCL_T' 
        MINUS
        SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH 
            FROM DBA_TAB_COLUMNS
            WHERE TABLE_NAME='AP_AUTO_APRV_EXCL_T'
    )
) ORDER BY TABLE_NAME, COLUMN_NAME;


--Shows each table individually for verification.
SELECT TABLE_NAME AS "KFS3 TABLE_NAME"        ,COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS          WHERE TABLE_NAME = 'AP_AUTO_APRV_EXCL_T' ORDER BY COLUMN_NAME;
SELECT TABLE_NAME AS "Financials 7 TABLE_NAME",COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM DBA_TAB_COLUMNS@KFS7GOLD WHERE TABLE_NAME = 'AP_AUTO_APRV_EXCL_T' ORDER BY COLUMN_NAME;

--Because there are column differences, only the columns that match can be compared.
--Table Data Comparison Example.
SELECT ACCOUNT_NBR, DOBJ_MAINT_CD_ACTV_IND, FIN_COA_CD, OBJ_ID, VER_NBR
    FROM AP_AUTO_APRV_EXCL_T 
MINUS
SELECT ACCOUNT_NBR, DOBJ_MAINT_CD_ACTV_IND, FIN_COA_CD, OBJ_ID, VER_NBR
    FROM AP_AUTO_APRV_EXCL_T@KFS7GOLD;
 