set colsep ','
set pagesize 0
set trimspool on
set headsep off
set numwidth 20

SELECT CURRENT_TIMESTAMP FROM DUAL;


spool ./data/ALL_PDP_PMT_DTL_T_3.csv
SELECT CUST_PMT_DOC_NBR,FDOC_TYP_CD,FS_ORIGIN_CD,INV_DT,INV_NBR,INV_TOT_DSCT_AMT,INV_TOT_OTHR_CRDT_AMT,INV_TOT_OTHR_DEBIT_AMT,INV_TOT_SHP_AMT,LST_UPDT_TS,NET_PMT_AMT,OBJ_ID,ORG_DOC_NBR,ORIG_INV_AMT,PDP_PRM_PMT_CNCL_IND,PMT_DTL_ID,PMT_GRP_ID,PO_NBR,REQS_NBR,VER_NBR FROM PDP_PMT_DTL_T ORDER BY OBJ_ID;
spool off

spool ./data/ALL_PDP_PMT_DTL_T_7.csv
SELECT CUST_PMT_DOC_NBR,FDOC_TYP_CD,FS_ORIGIN_CD,INV_DT,INV_NBR,INV_TOT_DSCT_AMT,INV_TOT_OTHR_CRDT_AMT,INV_TOT_OTHR_DEBIT_AMT,INV_TOT_SHP_AMT,LST_UPDT_TS,NET_PMT_AMT,OBJ_ID,ORG_DOC_NBR,ORIG_INV_AMT,PDP_PRM_PMT_CNCL_IND,PMT_DTL_ID,PMT_GRP_ID,PO_NBR,REQS_NBR,VER_NBR FROM PDP_PMT_DTL_T@DBLINK ORDER BY OBJ_ID;
spool off



spool ./data/ROW_COUNT_PDP_PMT_DTL_T_3.csv
SELECT COUNT(*) FROM PDP_PMT_DTL_T;
spool off

spool ./data/ROW_COUNT_PDP_PMT_DTL_T_7.csv
SELECT COUNT(*) FROM PDP_PMT_DTL_T@DBLINK;
spool off
