set colsep ','
set pagesize 0
set trimspool on
set headsep off
set numwidth 20

SELECT CURRENT_TIMESTAMP FROM DUAL;


spool ./data/ALL_LD_A21_REPORT_T_3.csv
SELECT A21LBR_RPT_PRD_TTL,A21LBR_RPT_RTRN_DT,A21_LBR_RPT_NBR,A21_LBR_RPT_TYP_CD,LBR_ET_FSCL_PRD_CD,LBR_ET_FSCL_YR,LBR_RPT_BEG_FSCL_PRD_CD,LBR_RPT_BEG_FSCL_YR,LBR_RPT_END_FSCL_PRD_CD,LBR_RPT_END_FSCL_YR,LBR_RPT_PRDSTAT_CD,OBJ_ID,ROW_ACTV_IND,UNIV_FISCAL_YR,VER_NBR FROM LD_A21_REPORT_T ORDER BY OBJ_ID;
spool off

spool ./data/ALL_LD_A21_REPORT_T_7.csv
SELECT A21LBR_RPT_PRD_TTL,A21LBR_RPT_RTRN_DT,A21_LBR_RPT_NBR,A21_LBR_RPT_TYP_CD,LBR_ET_FSCL_PRD_CD,LBR_ET_FSCL_YR,LBR_RPT_BEG_FSCL_PRD_CD,LBR_RPT_BEG_FSCL_YR,LBR_RPT_END_FSCL_PRD_CD,LBR_RPT_END_FSCL_YR,LBR_RPT_PRDSTAT_CD,OBJ_ID,ROW_ACTV_IND,UNIV_FISCAL_YR,VER_NBR FROM LD_A21_REPORT_T@DBLINK ORDER BY OBJ_ID;
spool off





