set colsep ','     
set pagesize 0   
set trimspool on 
set headsep off     

SELECT CURRENT_TIMESTAMP FROM DUAL;


spool ./data/CM_AST_PAYMENT_T_3.csv

select SUM(PTLAST_NBR),
SUM(CCT_CHARGE_AMT),
SUM(ST_DEPR1_BASE_AMT),
SUM(ST_ACUM_DEPR1_AMT),
SUM(ST_PRVYRDEPR1_AMT),
SUM(ST_PRD1_DEPR1_AMT),
SUM(ST_PRD2_DEPR1_AMT),
SUM(ST_PRD3_DEPR1_AMT),
SUM(ST_PRD4_DEPR1_AMT),
SUM(ST_PRD5_DEPR1_AMT),
SUM(ST_PRD6_DEPR1_AMT),
SUM(ST_PRD7_DEPR1_AMT),
SUM(ST_PRD8_DEPR1_AMT),
SUM(ST_PRD9_DEPR1_AMT),
SUM(ST_PRD10DEPR1_AMT),
SUM(ST_PRD11DEPR1_AMT),
SUM(ST_PRD12DEPR1_AMT)
from CM_AST_PAYMENT_T;

spool off


spool ./data/CM_AST_PAYMENT_T_7.csv

select SUM(PTLAST_NBR),
SUM(CCT_CHARGE_AMT),
SUM(ST_DEPR1_BASE_AMT),
SUM(ST_ACUM_DEPR1_AMT),
SUM(ST_PRVYRDEPR1_AMT),
SUM(ST_PRD1_DEPR1_AMT),
SUM(ST_PRD2_DEPR1_AMT),
SUM(ST_PRD3_DEPR1_AMT),
SUM(ST_PRD4_DEPR1_AMT),
SUM(ST_PRD5_DEPR1_AMT),
SUM(ST_PRD6_DEPR1_AMT),
SUM(ST_PRD7_DEPR1_AMT),
SUM(ST_PRD8_DEPR1_AMT),
SUM(ST_PRD9_DEPR1_AMT),
SUM(ST_PRD10DEPR1_AMT),
SUM(ST_PRD11DEPR1_AMT),
SUM(ST_PRD12DEPR1_AMT)
from CM_AST_PAYMENT_T@DBLINK;

spool off
