set colsep ','     
set pagesize 0   
set trimspool on 
set headsep off     

SELECT CURRENT_TIMESTAMP FROM DUAL;


spool ./data/CM_CPTLAST_DTL_T_3.csv

select 
RPAD(FDOC_NBR, '5'),
RPAD(OBJ_ID, '5'),
RPAD(VER_NBR, '5'),
RPAD(CAMPUS_CD, '5'),
RPAD(BLDG_CD, '5'),
RPAD(CPTLAST_SERIAL_NBR, '5'),
RPAD(BLDG_ROOM_NBR, '5'),
RPAD(BLDG_SUB_ROOM_NBR, '5'),
RPAD(CPTLAST_TAG_NBR, '5'),
RPAD(ORG_INVN_NM, '5'),
RPAD(ORG_CPTLAST_TYP_ID, '5'),
RPAD(AST_OFFCMP_NM, '5'),
RPAD(AST_OFFCMP_ADDR, '5'),
RPAD(AST_OFFCMP_CITY_NM, '5'),
RPAD(AST_OFFCMP_ST_CD, '5'),
RPAD(AST_OFFCMP_ZIP_CD, '5'),
RPAD(AST_OFFCMP_CNTRY_CD, '5'),
RPAD(CPTL_AST_GOV_TAG_NBR, '5'),
RPAD(CPTL_AST_NTL_STOCK_NBR, '5'),
RPAD(AST_REP_UNVL_ID, '5'),
RPAD(CPTLAST_TYP_CD, '5'),
RPAD(CPTLAST_DESC, '5'),
RPAD(CPTLAST_MFR_NM, '5'),
RPAD(ORG_TXT, '5'),
RPAD(CPTLAST_MFRMDL_NBR, '5'),
RPAD(SEP_SRC_AMT, '5')
from CM_CPTLAST_DTL_T;

spool off


SELECT CURRENT_TIMESTAMP FROM DUAL;


spool ./data/CM_CPTLAST_DTL_T_3.csv

select 
RPAD(FDOC_NBR, '5'),
RPAD(OBJ_ID, '5'),
RPAD(VER_NBR, '5'),
RPAD(CAMPUS_CD, '5'),
RPAD(BLDG_CD, '5'),
RPAD(CPTLAST_SERIAL_NBR, '5'),
RPAD(BLDG_ROOM_NBR, '5'),
RPAD(BLDG_SUB_ROOM_NBR, '5'),
RPAD(CPTLAST_TAG_NBR, '5'),
RPAD(ORG_INVN_NM, '5'),
RPAD(ORG_CPTLAST_TYP_ID, '5'),
RPAD(AST_OFFCMP_NM, '5'),
RPAD(AST_OFFCMP_ADDR, '5'),
RPAD(AST_OFFCMP_CITY_NM, '5'),
RPAD(AST_OFFCMP_ST_CD, '5'),
RPAD(AST_OFFCMP_ZIP_CD, '5'),
RPAD(AST_OFFCMP_CNTRY_CD, '5'),
RPAD(CPTL_AST_GOV_TAG_NBR, '5'),
RPAD(CPTL_AST_NTL_STOCK_NBR, '5'),
RPAD(AST_REP_UNVL_ID, '5'),
RPAD(CPTLAST_TYP_CD, '5'),
RPAD(CPTLAST_DESC, '5'),
RPAD(CPTLAST_MFR_NM, '5'),
RPAD(ORG_TXT, '5'),
RPAD(CPTLAST_MFRMDL_NBR, '5'),
RPAD(SEP_SRC_AMT, '5')
from CM_CPTLAST_DTL_T;

spool off
