set colsep ','
set pagesize 0
set trimspool on
set headsep off
set numwidth 20

SELECT CURRENT_TIMESTAMP FROM DUAL;

--ACTN_ITM_ID, ACTN_RQST_ID, DOC_HDR_ID, and RSP_ID were converted from NUMBER to VARCHAR2, requiring use of the TO_CHAR() method to ensure data is presented the same in both SELECT results.

spool ./data/ALL_KREW_ACTN_ITM_T_3.csv
SELECT TO_CHAR(ACTN_ITM_ID),TO_CHAR(ACTN_RQST_ID),ASND_DT,DLGN_GRP_ID,DLGN_PRNCPL_ID,DLGN_TYP,DOC_HDLR_URL,TO_CHAR(DOC_HDR_ID),DOC_HDR_TTL,DOC_TYP_LBL,DOC_TYP_NM,DTYPE,GRP_ID,PRNCPL_ID,ROLE_NM,RQST_CD,RQST_LBL,TO_CHAR(RSP_ID),VER_NBR FROM KREW_ACTN_ITM_T ORDER BY 1;
spool off

spool ./data/ALL_KREW_ACTN_ITM_T_7.csv
SELECT ACTN_ITM_ID,ACTN_RQST_ID,ASND_DT,DLGN_GRP_ID,DLGN_PRNCPL_ID,DLGN_TYP,DOC_HDLR_URL,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_TYP_NM,DTYPE,GRP_ID,PRNCPL_ID,ROLE_NM,RQST_CD,RQST_LBL,RSP_ID,VER_NBR FROM rice.KREW_ACTN_ITM_T@KFS7GOLD ORDER BY 1;
spool off
